[versions]
agp = "8.13.2"
cucumberAndroid = "7.18.1"
kotlin = "2.0.21"
coreKtx = "1.10.1"
junitJupiter = "5.11.4"
espressoCore = "3.6.1"
testRunner = "1.6.1"
testRules = "1.6.1"
lifecycleRuntimeKtx = "2.6.1"
activityCompose = "1.8.0"
composeBom = "2024.09.00"
assertj = "3.27.3"
mockk = "1.13.13"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.17.0" }
cucumber-android = { module = "io.cucumber:cucumber-android", version.ref = "cucumberAndroid" }
cucumber-junit = { module = "io.cucumber:cucumber-junit", version.ref = "cucumberAndroid" }
cucumber-picocontainer = { module = "io.cucumber:cucumber-picocontainer", version.ref = "cucumberAndroid" }
# JUnit 5 (Jupiter)
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junitJupiter" }
# Needed by Gradle to discover/run tests on the JUnit platform
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version = "1.13.0" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version = "1.3.0" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version = "3.7.0" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version = "2.10.0" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version = "1.12.2" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version = "2025.12.01" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-test-runner = { group = "androidx.test", name = "runner", version = "1.7.0" }
androidx-test-rules = { group = "androidx.test", name = "rules", version = "1.7.0" }
assertj-core = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
mockk-core = { group = "io.mockk", name = "mockk", version.ref = "mockk" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
